-- v2: 로그인 없는 공개형 모임 운영 웹앱
-- Supabase SQL Editor에서 실행하세요.

create table if not exists public.meetings (
  id uuid primary key default gen_random_uuid(),
  project text not null default '기타',
  title text not null,
  meeting_date date not null default current_date,
  start_time time,
  location text default '',
  attendees text default '',
  summary text default '',
  discussion text default '',
  decisions text default '',
  actions jsonb not null default '[]'::jsonb,
  links text default '',
  author text default '익명',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.meeting_revisions (
  id bigint generated by default as identity primary key,
  meeting_id uuid not null references public.meetings(id) on delete cascade,
  snapshot jsonb not null,
  editor text default '익명',
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text default '',
  pinned boolean not null default false,
  author text default '익명',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedules (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  event_date date not null,
  event_time time,
  location text default '',
  note text default '',
  is_public boolean not null default false,
  author text default '익명',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- v10: 일정은 기본 비공개. Arena에는 공개 체크된 일정만 노출합니다.
alter table public.schedules add column if not exists is_public boolean not null default false;
create index if not exists idx_schedules_public_date on public.schedules(is_public, event_date, event_time);

create or replace view public.arena_public_schedules as
select id, title, event_date, event_time, location, note, author, created_at, updated_at
from public.schedules
where is_public = true;



create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null default '',
  author text default '익명',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  body text not null,
  author text default '익명',
  created_at timestamptz not null default now()
);

create index if not exists idx_post_comments_post_id_created_at
on public.post_comments(post_id, created_at);

create table if not exists public.post_polls (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null unique references public.posts(id) on delete cascade,
  question text not null,
  closed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.post_poll_options (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.post_polls(id) on delete cascade,
  option_text text not null,
  sort_order integer not null default 0
);

create index if not exists idx_post_poll_options_poll_sort
on public.post_poll_options(poll_id, sort_order);

create table if not exists public.post_poll_votes (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.post_polls(id) on delete cascade,
  option_id uuid not null references public.post_poll_options(id) on delete cascade,
  voter_id text not null,
  created_at timestamptz not null default now(),
  unique (poll_id, voter_id)
);

create index if not exists idx_post_poll_votes_poll
on public.post_poll_votes(poll_id);

create table if not exists public.todos (
  id uuid primary key default gen_random_uuid(),
  task text not null,
  owner text default '',
  due date,
  project text default '',
  note text default '',
  done boolean not null default false,
  author text default '익명',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create table if not exists public.todo_comments (
  id uuid primary key default gen_random_uuid(),
  todo_key text not null,
  body text not null,
  author text default '익명',
  created_at timestamptz not null default now()
);

create index if not exists idx_todo_comments_todo_key_created_at
on public.todo_comments(todo_key, created_at);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end;
$$;

create or replace function public.keep_meeting_revision()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.meeting_revisions(meeting_id,snapshot,editor)
  values(old.id,to_jsonb(old),coalesce(new.author,old.author,'익명'));
  new.updated_at:=now();
  return new;
end;
$$;

drop trigger if exists trg_keep_meeting_revision on public.meetings;
create trigger trg_keep_meeting_revision before update on public.meetings for each row execute function public.keep_meeting_revision();

drop trigger if exists trg_announcement_touch on public.announcements;
create trigger trg_announcement_touch before update on public.announcements for each row execute function public.touch_updated_at();

drop trigger if exists trg_schedule_touch on public.schedules;
create trigger trg_schedule_touch before update on public.schedules for each row execute function public.touch_updated_at();

drop trigger if exists trg_post_touch on public.posts;
create trigger trg_post_touch before update on public.posts for each row execute function public.touch_updated_at();

drop trigger if exists trg_todo_touch on public.todos;
create trigger trg_todo_touch before update on public.todos for each row execute function public.touch_updated_at();

alter table public.meetings enable row level security;
alter table public.meeting_revisions enable row level security;
alter table public.announcements enable row level security;
alter table public.schedules enable row level security;
alter table public.posts enable row level security;
alter table public.post_comments enable row level security;
alter table public.post_polls enable row level security;
alter table public.post_poll_options enable row level security;
alter table public.post_poll_votes enable row level security;
alter table public.todos enable row level security;
alter table public.todo_comments enable row level security;

drop policy if exists "public read meetings" on public.meetings;
drop policy if exists "public insert meetings" on public.meetings;
drop policy if exists "public update meetings" on public.meetings;
drop policy if exists "public read revisions" on public.meeting_revisions;
drop policy if exists "public all announcements" on public.announcements;
drop policy if exists "public all schedules" on public.schedules;
drop policy if exists "public all posts" on public.posts;
drop policy if exists "public all post comments" on public.post_comments;
drop policy if exists "public all post polls" on public.post_polls;
drop policy if exists "public all post poll options" on public.post_poll_options;
drop policy if exists "public all post poll votes" on public.post_poll_votes;
drop policy if exists "public all todos" on public.todos;
drop policy if exists "public all todo comments" on public.todo_comments;

create policy "public read meetings" on public.meetings for select to anon using(true);
create policy "public insert meetings" on public.meetings for insert to anon with check(true);
create policy "public update meetings" on public.meetings for update to anon using(true) with check(true);
create policy "public read revisions" on public.meeting_revisions for select to anon using(true);

create policy "public all announcements" on public.announcements for all to anon using(true) with check(true);
create policy "public all schedules" on public.schedules for all to anon using(true) with check(true);
create policy "public all posts" on public.posts for all to anon using(true) with check(true);
create policy "public all post comments" on public.post_comments for all to anon using(true) with check(true);
create policy "public all post polls" on public.post_polls for all to anon using(true) with check(true);
create policy "public all post poll options" on public.post_poll_options for all to anon using(true) with check(true);
create policy "public all post poll votes" on public.post_poll_votes for all to anon using(true) with check(true);
create policy "public all todos" on public.todos for all to anon using(true) with check(true);
create policy "public all todo comments" on public.todo_comments for all to anon using(true) with check(true);

grant usage on schema public to anon;
grant select,insert,update on public.meetings to anon;
grant select on public.meeting_revisions to anon;
grant select,insert,update,delete on public.announcements to anon;
grant select,insert,update,delete on public.schedules to anon;
grant select on public.arena_public_schedules to anon;
grant select,insert,update,delete on public.posts to anon;
grant select,insert,update,delete on public.post_comments to anon;
grant select,insert,update,delete on public.post_polls to anon;
grant select,insert,update,delete on public.post_poll_options to anon;
grant select,insert,update,delete on public.post_poll_votes to anon;
grant select,insert,update,delete on public.todos to anon;
grant select,insert,update,delete on public.todo_comments to anon;
grant usage,select on sequence public.meeting_revisions_id_seq to anon;

-- 요청대로 로그인 없이 공개 읽기/쓰기를 허용하는 구조입니다.
